services:
  - type: web
    name: dapur-nusantara-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        value: https://dapur-nusantara.vercel.app
